@tool
class_name EditorShorcut
extends Resource


@export var quit_editor : Shortcut
@export var new_project : Shortcut
@export var open_project : Shortcut
@export var save : Shortcut
@export var save_as : Shortcut
@export var quick_export : Shortcut
@export var undo : Shortcut
@export var redo : Shortcut
@export var copy : Shortcut
@export var cut : Shortcut
@export var paste : Shortcut
@export var confirm : Shortcut
@export var arrow_left : Shortcut
@export var arrow_up : Shortcut
@export var arrow_right : Shortcut
@export var arrow_down : Shortcut
@export var arrow_left_variant : Shortcut
@export var arrow_up_variant : Shortcut
@export var arrow_right_variant : Shortcut
@export var arrow_down_variant : Shortcut
@export var view_show_grid : Shortcut
@export var view_show_tile : Shortcut
@export var rotate_canvas_90 : Shortcut
@export var rotate_canvas_min90 : Shortcut
@export var flip_canvas_horizontal : Shortcut
@export var flip_canvas_vertical : Shortcut
@export var reset_canvas_transform : Shortcut
@export var toggle_tint_layer : Shortcut
@export var toggle_edit_selection_only : Shortcut
@export var tool_select : Shortcut
@export var tool_selection : Shortcut
@export var tool_move : Shortcut
@export var tool_pan : Shortcut
@export var tool_pen : Shortcut
@export var tool_brush : Shortcut
@export var tool_stamp : Shortcut
@export var tool_eraser : Shortcut
@export var tool_magnet : Shortcut
@export var tool_rectangle : Shortcut
@export var tool_fill : Shortcut
@export var tool_inverse_selection : Shortcut
@export var tool_remove_selection : Shortcut
@export var tool_delete_selected : Shortcut
@export var tool_line : Shortcut
@export var tool_color_picker : Shortcut
@export var tool_zoom : Shortcut
@export var tool_ellipse : Shortcut
@export var animation_play_pause : Shortcut
@export var animation_shift_frame_left : Shortcut
@export var animation_shift_frame_right : Shortcut
@export var animation_move_frame_to_timeline : Shortcut
@export var animation_move_frame_to_draft : Shortcut
@export var animation_onion_skinning : Shortcut
@export var prev_toolbox : Shortcut
