class_name PixelPenEnum
extends RefCounted

enum ToolBoxGrup{
	TOOL_GRUP_UNKNOWN = -1,
	TOOL_GRUP_TOOLBOX,
	TOOL_GRUP_TOOLBOX_SUB_TOOL,
	TOOL_GRUP_LAYER,
	TOOL_GRUP_ANIMATION,
	TOOL_GRUP_TOOLBAR,
}

enum ToolBox{
	TOOL_UNKNOWN = -1,
	TOOL_SELECT,
	TOOL_MOVE,
	TOOL_PAN,
	TOOL_SELECTION,
	TOOL_PEN,
	TOOL_BRUSH,
	TOOL_STAMP,
	TOOL_ERASER,
	TOOL_MAGNET,
	TOOL_LINE,
	TOOL_ELLIPSE,
	TOOL_RECTANGLE,
	TOOL_FILL,
	TOOL_COLOR_PICKER,
	TOOL_ZOOM
}


enum ToolBoxSelect{
	TOOL_SELECT_UNKNOWN = -1,
	TOOL_SELECT_LAYER,
	TOOL_SELECT_COLOR,
	TOOL_SELECTION_COLOR_OPTION_ONLY_AXIS_YES,
	TOOL_SELECTION_COLOR_OPTION_ONLY_AXIS_NO
}


enum ToolBoxMove{
	TOOL_MOVE_UNKNOWN = -1,
	TOOL_MOVE_CUT,
	TOOL_MOVE_COPY,
	TOOL_MOVE_ROTATE_LEFT,
	TOOL_MOVE_ROTATE_RIGHT,
	TOOL_MOVE_FLIP_HORIZONTAL,
	TOOL_MOVE_FLIP_VERTICAL,
	TOOL_MOVE_CANCEL,
	TOOL_MOVE_COMMIT,
	TOOL_SCALE_LEFT,
	TOOL_SCALE_UP,
	TOOL_SCALE_RIGHT,
	TOOL_SCALE_DOWN
}

enum ToolBoxSelection{
	TOOL_SELECTION_UNKNOWN = -1,
	TOOL_SELECTION_UNION,
	TOOL_SELECTION_DIFFERENCE,
	TOOL_SELECTION_INTERSECTION,
	TOOL_SELECTION_CLOSE_POLYGON,
	TOOL_SELECTION_CANCEL_POLYGON,
	TOOL_SELECTION_INVERSE = 1001, # GLOBAL UNIQUE
	TOOL_SELECTION_REMOVE = 1002, # GLOBAL UNIQUE
	TOOL_SELECTION_DELETE_SELECTED = 1003 # GLOBAL UNIQUE
}

enum ToolBoxPen{
	TOOL_PEN_UNKNOWN = -1,
	TOOL_PEN_PIXEL_PERFECT_YES,
	TOOL_PEN_PIXEL_PERFECT_NO
}


enum ToolBoxMagnet{
	TOOL_MAGNET_UNKNOWN = -1,
	TOOL_MAGNET_CANCEL
}


enum ToolBoxLine{
	TOOL_LINE_UNKNOWN = -1,
	TOOL_LINE_PIXEL_PERFECT_YES,
	TOOL_LINE_PIXEL_PERFECT_NO
}


enum ToolBoxEllipse{
	TOOL_ELLIPSE_UNKNOWN = -1,
	TOOL_ELLIPSE_FILL_YES,
	TOOL_ELLIPSE_FILL_NO
}


enum ToolBoxRectangle{
	TOOL_RECTANGLE_UNKNOWN = -1,
	TOOL_RECTANGLE_FILL_YES,
	TOOL_RECTANGLE_FILL_NO
}


enum ToolBoxFill{
	TOOL_FILL_UNKNOWN = -1,
	TOOL_FILL_OPTION_ONLY_AXIS_YES,
	TOOL_FILL_OPTION_ONLY_AXIS_NO
}


enum ToolBoxZoom{
	TOOL_ZOOM_UNKNOWN = -1,
	TOOL_ZOOM_IN,
	TOOL_ZOOM_OUT,
}


enum ToolAnimation{
	TOOL_ANIMATION_UNKNOWN = -1,
	TOOL_ANIMATION_PLAY_PAUSE,
	TOOL_ANIMATION_SKIP_TO_FRONT,
	TOOL_ANIMATION_STEP_BACKWARD,
	TOOL_ANIMATION_STEP_FORWARD,
	TOOL_ANIMATION_SKIP_TO_END
}


enum ToolBar{
	TOOLBAR_UNKNOWN = -1,
	TOOLBAR_UNDO,
	TOOLBAR_RESET_ZOOM,
	TOOLBAR_REDO,
	TOOLBAR_SHOW_GRID,
	TOOLBAR_TOGGLE_TINT_BLACK_LAYER,
	TOOLBAR_SAVE,
}


enum ResizeAnchor{
	CENTER = 0,
	TOP_LEFT,
	TOP,
	TOP_RIGHT,
	RIGHT,
	BOTTOM_RIGHT,
	BOTTOM,
	BOTTOM_LEFT,
	LEFT
}
