name: 🍎 Build MacOS
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: 🍎 MacOS ${{ matrix.arch }} ${{ matrix.target }}

    strategy:
      fail-fast: false
      matrix:
        platform: [macos]
        precision : [single]
        target: [debug, release]
        arch: [universal]

    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 🔗 GDExtension Build
        uses: pixelpen-dev/pixelpen/.github/actions/gdextension@main
        with:
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          float-precision: ${{ matrix.precision }}
          build-target-type: 'template_${{ matrix.target }}'

      - name: Include Files
        shell: sh
        run: |
          cp '${{ github.workspace }}/README.md' '${{ github.workspace }}/LICENSE.txt' ${{ github.workspace }}/project/addons/net.yarvis.pixel_pen/

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: pixelpen-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.target }}
          path: |
            ${{ github.workspace }}/project/

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: ${{ github.event.repository.name }}
          pattern: pixelpen-*
          delete-merged: true