name: 🛠️ Build All
on: [workflow_dispatch, workflow_call, pull_request]

jobs:
  build:
    name: ${{ matrix.name }} ${{ matrix.target }}

    strategy:
      fail-fast: false
      matrix:
        identifier: [linux, windows, windows32, macos, web, android-arm32, android-arm64]
        precision : [single]
        target: [debug, release]
        include:
          - identifier: linux
            platform: linux
            name: 🐧 Linux
            runner: ubuntu-latest
            arch: x86_64
            
          - identifier: windows
            platform: windows
            name: 🪟 Windows64
            runner: windows-latest
            arch: x86_64
          
          - identifier: windows32
            platform: windows
            name: 🪟 Windows32
            runner: windows-latest
            arch: x86_32

          - identifier: macos
            platform: macos
            name: 🍎 macOS
            runner: macos-latest
            arch: universal

          - identifier: web
            platform: web
            name: 🌐 Web
            runner: ubuntu-latest
            arch: wasm32

          - identifier: android-arm64
            platform: android
            name: 🤖 Android Arm64
            runner: ubuntu-latest
            arch: arm64

          - identifier: android-arm32
            platform: android
            name: 🤖 Android Arm32
            runner: ubuntu-latest
            arch: arm32

    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 🔗 GDExtension Build
        uses: godotengine/godot-cpp-template/.github/actions/build@main
        with:          
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          float-precision: ${{ matrix.precision }}
          build-target-type: 'template_${{ matrix.target }}'

      - name: Include Files (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Copy-Item -Path "${{ github.workspace }}/README.md" -Destination "${{ github.workspace }}/project/addons/net.yarvis.pixel_pen/"
          Copy-Item -Path "${{ github.workspace }}/LICENSE.txt" -Destination "${{ github.workspace }}/project/addons/net.yarvis.pixel_pen/"

      - name: Include Files
        if: runner.os != 'Windows'
        shell: sh
        run: |
          cp '${{ github.workspace }}/README.md' '${{ github.workspace }}/LICENSE.txt' ${{ github.workspace }}/project/addons/net.yarvis.pixel_pen/

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: pixelpen-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.target }}
          path: |
            ${{ github.workspace }}/project/

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: ${{ github.event.repository.name }}
          pattern: pixelpen-*
          delete-merged: true